---
abstract: 'A perl blog engine.'
author:
  - 'Adam Stokes <hackr@cypherbook.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-skryf
requires:
  Carp: 0
  DateTime: 0
  Exporter: 0
  File::ShareDir: 0
  FindBin: 0
  List::Objects::WithUtils: 0
  Mojo::Base: 0
  Mojolicious::Lite: 0
  Mojolicious::Plugin::Blog: 0
  Mojolicious::Plugin::Gravatar: 0
  Path::Tiny: 0
  Rex: 0
  Rex::Config: 0
  Text::Markdown: 0
  base: 0
  perl: v5.16.3
  strictures: 1
  vars: 0
resources:
  homepage: https://github.com/battlemidget/App-skryf
  repository: https://github.com/battlemidget/App-skryf.git
version: 0.005
