---
abstract: 'perl blogger'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.024
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-skryf
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: 0
  Data::Printer: 0
  DateTime: 0
  DateTime::Format::ISO8601: 0
  File::ShareDir: 0
  FindBin: 0
  List::Objects::WithUtils: 0
  Mojo::Base: 0
  Mojolicious::Lite: 0
  Mojolicious::Plugin::Disqus::Tiny: 0
  Mojolicious::Plugin::GoogleAnalytics: 0
  Mojolicious::Plugin::Gravatar: 0
  Path::Tiny: 0
  Pithub: 0
  Text::Markdown: 0
resources:
  bugtracker: https://github.com/battlemidget/App-skryf/issues
  homepage: https://github.com/battlemidget/App-skryf
  repository: https://github.com/battlemidget/App-skryf.git
version: 0.007_4
