---
abstract: 'i kno rite. another perl cms.'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.025
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.3, Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-skryf
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: 0
  DateTime: 0
  DateTime::Format::RFC3339: 0
  File::ShareDir: 0
  FindBin: 0
  Mango: 0
  Method::Signatures: 0
  Mojo::Base: 0
  Mojolicious: 0
  Mojolicious::Plugin::CSRFDefender: 0
  Mojolicious::Plugin::Disqus::Tiny: 0
  Mojolicious::Plugin::GoogleAnalytics: 0
  Mojolicious::Plugin::Gravatar: 0
  Path::Tiny: 0
  String::Dirify: 0
  String::Util: 0
  Text::MultiMarkdown: 0
  XML::Atom::SimpleFeed: 0
resources:
  bugtracker: https://github.com/battlemidget/App-skryf/issues
  homepage: https://github.com/battlemidget/App-skryf
  repository: https://github.com/battlemidget/App-skryf.git
version: 0.011_14
x_contributors:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
